package me.cloyd1815.signage.sign;

public enum SignType {
	WEEKLY_SPECIAL_FULL,
	WEEKLY_SPECIAL_HALF,
	WEEKLY_SPECIAL_QUARTER,
	SAVE_MORE_FULL,
	SAVE_MORE_HALF,
	SAVE_MORE_QUARTER,
	REGULAR_PRICE_FULL,
	REGULAR_PRICE_HALF,
	REGULAR_PRICE_QUATER,
	FARM_FRESH_FULL,
	FARM_FRESH_HALF,
	FARM_FRESH_QUARTER
}
